# data
input_dataset: "/root/blog-multi-label/output/reddit_aus_finance.csv"
text_col: "text"
label_col: "label"
group: "annotation_2"
output_dir: "/root/blog-multi-label/output/"

# preprocessing
min_tokens: 5
max_tokens: 50

# classifier
classifier_type: "multi_label"
label_dictionary:
  workplace: ['WFH', 'boss', 'co-workers', 'culture', 'hybrid', 'life balance', 'office', 'culture']
  property: ['suburb', 'area', 'lend', 'report', 'agent', 'auction', 'bedroom', 'boom', 'builder', 'defect', 'floor plan', 'house', 'landlord', 'layout', 'loan', 'mortgage', 'property', 'real estate', 'refinance', 'rent', 'resident', 'townhouse']
  tax: ['gst', 'land tax', 'salary sacrifice', 'tax', 'franking', 'treaty', 'taxable', 'tax return']
  insurance: ['income protection', 'indemnity', 'insurance']
  super: ['contribution', 'fund', 'pension', 'retire', 'self-funded', 'super', 'after tax', 'concessional', 'accumulation']
  inflation: ['inflation', 'interest rates', 'petrol', 'phillip lowe', 'reserve bank', 'cost of living', 'expensive', 'rise', 'rising']
  stocks: ['200','asx', 'commsec', 'dip', 'dividends', 'etf', 'high growth', 'indexed', 'invest', 'return', 'securities', 'selfwealth', 'shares', 'stock', 'van guard', 'vdhg', 'diversification', 'portfolio']
  toxic: ['bro', 'butt', 'fool', 'fuck', 'laughable', 'lol', 'salty', 'shit', 'tard']

# annotation
n_examples: 10
prediction_threshold: 0.7
rank_candidates: True
max_candidates: 15