# data
dataset: "/Users/samhardyhey/Desktop/blog/blog-multi-label/output/aus_finance_reddit.csv"
text_col: "text"
label_col: "label"
output: "/Users/samhardyhey/Desktop/blog/blog-multi-label/output/aus_finance_reddit_annotated.csv"

# classifier
classifier_type: "multi_label"
label_dictionary:
  customer_service: ["customer service", "service", "experience"]

# annotation
n_examples: 2
prediction_threshold: 0.70
rank_candidates: True
max_candidates: 10
